version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9-bullseye
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install latest influxdb
          command: |
            # https://docs.influxdata.com/influxdb/v1.8/introduction/install/
            wget -q https://repos.influxdata.com/influxdata-archive_compat.key
            echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
            echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
            apt-get update
            apt-get install -y influxdb
      - run:
          name: install dev/test requirements
          command: |
            apt-get install -y python3 python3-pip
            pip3 install -r requirements-test.txt
      - python/save-cache
      - run:
          name: lint checks
          command: |
            for f in `find ./ -name '*py' | grep -v test | grep -v venv`; do pyflakes $f; done
      - run:
          name: run tests
          command: |
            /etc/init.d/influxdb start  # just to make sure?
            coverage run --source=candles -m pytest

      - store_test_results:
          path: .coverage
      - store_artifacts:
          path: .coverage
          destination: .coverage
      - run:
          name: coveralls upload
          command: |
            COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} coveralls

workflows:
  main:
    jobs:
      - build-and-test
